re PR target/27880 (undefined reference to `_Unwind_GetIPInfo')
	PR  target/27880
	* config/unwind_ipinfo.m4 (GCC_CHECK_UNWIND_GETIPINFO): Change from
	link test to target based test.
	* libstdc++/v3/configure.ac: Move call to GCC_CHECK_UNWIND_GETIPINFO.
	* libstdc++/v3/configure: Regenerate.
	* libjava/configure: Regenerate.

From-SVN: r141804